### ISSUE TITLE
Make extensions an Enum, with special case for Unknown instead of boxed traits

### ISSUE THREAD

**Issue by jadamcrain** [jadamcrain/rasn#2]

**Comment by Mayday646** [comment]
I have some questions about [opendnp3](https://github.com/dnp3/opendnp3). Because this library is set to read-only and I cannot find your contact information, I can only leave you a message here. I am so sorry;

[OctetData.cpp](https://github.com/dnp3/opendnp3/blob/release/cpp/lib/src/app/OctetData.cpp)This file was last uploaded by you, and the problem I encountered was how to write `OctetString`
```c++
class ReadHandler: public ISOEHandler {
private:
    void Process(const HeaderInfo &info, const ICollection<Indexed<OctetString>> &values) override;
    template <class T>
    std::string valueToString(const T &meas)
    {
        std::ostringstream oss;
        oss << meas.value;
        return oss.str();
    }
public:
    std::vector<const uint8_t *> octStrings_;
    static std::shared_ptr<ISOEHandler> CreateInstance()
    {
        return std::make_shared<ReadHandler>();
    }
};
void ReadHandler::Process(const HeaderInfo &info, const ICollection<Indexed<OctetString>> &values)
{
    values.ForeachItem([&](const Indexed<OctetString> &pair) {
        octStrings_.emplace_back(pair.value.ToBuffer().data);
    });
}
```
`OctetString` content can be read normally through subscripts and stored in a container
---
```c++     
    master->PerformFunction("OctetStrings",
                            FunctionCode::WRITE,
                            { Header::Range16(110, 0, 0, 8) });

   //OctetString: GroupVariation::Group110Var0
       
```

Attempting to write `OctetString` data using this API failed;
I don't know how to use this API to write `OctetString`, or there are other ways to write them;
I would greatly appreciate it if you could reply or provide other assistance.

**Comment by jadamcrain** [comment]
Per https://dnp3.github.io/ OpenDNP3 is end-of-life. I don't support it anymore.
